import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Separator } from "@/components/ui/separator";
import Link from "next/link";
import QueryProvider from "@/providers/query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "-",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <section className="p-4 gap-4 flex flex-row">
            <Link href="/dashboard" className="text-lg hover:underline">Dashboard</Link>
            <Link href="/transaction" className="text-lg hover:underline">Transaction</Link>
            <Link href="/card" className="text-lg hover:underline">Card</Link>
          </section>
          <Separator />
          <section className="m-4">
            {children}
          </section>
        </QueryProvider>
      </body>
    </html>
  );
}
